name: Build

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Echo
        run: |
          echo ${{ github.workspace }}
