name: Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "frontend/**"
      - "backend/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    outputs:
      diff: ${{ toJSON(steps.*.outputs.diff) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: frontend
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.event.after}} \
            ./.github/workflows/build.yml \
            ./frontend
          if [[ $? -eq 1 ]]; then
            echo "diff=frontend" >> $GITHUB_OUTPUT
          else
            echo "diff=" >> $GITHUB_OUTPUT
          fi
      - id: backend
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.event.after}} \
            ./.github/workflows/build.yml \
            ./backend
          if [[ $? -eq 1 ]]; then
            echo "diff=backend" >> $GITHUB_OUTPUT
          else
            echo "diff=" >> $GITHUB_OUTPUT
          fi

  build_frontend:
    runs-on: ubuntu-latest
    needs: check
    if: contains(needs.check.outputs.diff, 'frontend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cat frontend workspace
        run: |
          cat ./frontend/keep

  build_backend:
    runs-on: ubuntu-latest
    needs: check
    if: contains(needs.check.outputs.diff, 'backend')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cat backend workspace
        run: |
          cat ./backend/keep
