name: Build2

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "frontend/**"
      - "backend/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      updated: ${{ steps.filter.outputs.changes != '[]' }}
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # "Warning: Unexpected input(s) 'predicate-quantifier'"は無視すること
          # https://github.com/dorny/paths-filter/issues/225
          predicate-quantifier: "every"
          filters: .github/filters.yml

  display_outputs:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Display outputs
        run: |
          echo "needs.check.outputs.changes: ${{ needs.check.outputs.changes }}"
          echo "needs.check.outputs.updated: ${{ needs.check.outputs.updated }}"
          echo "needs.check.outputs.frontend: ${{ needs.check.outputs.frontend }}"
          echo "needs.check.outputs.backend: ${{ needs.check.outputs.backend }}"

  build_frontend:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.frontend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cat frontend workspace
        run: |
          cat ./frontend/keep

  build_backend:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.backend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cat backend workspace
        run: |
          cat ./backend/keep
